# Matriks invers  
Matrik invers merupakan kebalikan dari suatu matriks, ketika matriks tersebut dikalikan dengan matriks inversnya akan menghasilkan matriks identitas. Matriks invers disimbolkan dengan $A^{-1}$. Matriks invers hanya berlaku pada matriks persegi yang memiliki jumlah baris dan kolom yang sama dan determinanya tidak nol.  
misal kita memiliki matriks A dan matriks inversnya $A^{-1}$, maka berlaku persamaan:
$A\times A^{-1}=A^{-1}\times A=I$ 
(merupakan matriks identitas.)  

## Sifat-sifat Matriks  
JIka A merupakan matrik invers, k bilangan bulat positif, dan c adalah skalar $\neq 0$ maka
1. $A^{-1}$ diinverskan menjadi $(A^{-1})^{-1}=A$
2. $A^{k}$ diinverskan menjadi $(A^{k})^{-1}=A^{k} A^{k} A^{k}=(A^{-1})^{k}=A^{-k}$
3. $cA$ diinverskan dan $(cA)^{-1}=\frac{1}{c}  A^{-1}, c\neq 0$
4. $A^{T}$ diinverskan dan $(A^{T})^{-1}=(A^{-1})^{T}$

## Mencari matrik invers dengan eliminasi gauss jordan  

Metode Gauss-Jordan adalah sebuah teknik aljabar linear untuk menyelesaikan sistem persamaan linear dan mencari invers dari matriks persegi.  Inti dari metode ini adalah memanipulasi matriks menggunakan operasi baris elementer (OBE) secara sistematis. 

### Contoh penyelesaian mencari matriks invers dengan gauss jordan   

1. bentuk matriks identitas I dengan ukuran yang sama dengan matriks $A=\begin{bmatrix}
2 &2\\
3 & 1
\end{bmatrix}$
2. menggabungkan Matriks A dengan matriks identitas.  
$$
\begin{equation*}
A=
\begin{bmatrix}
2&2& | &1&0 \\
3&1& | &0&1
\end{bmatrix}
\end{equation*}
$$
3. lakukan operasi per baris pada matriks tersebut menjadi identitas dengan Eliminasi Gauss Jordan .  
a. kali baris 1 dengan 1/2 (R1=1/2R1)
$$
\begin{equation*}
A=
\begin{bmatrix}
2&2& | &1&0 \\
3&1& | &0&1
\end{bmatrix}
\end{equation*}
$$
b. Kurangi baris 2 dengan (R2 = R2-3R1)
$$
\begin{equation*}
A=
\begin{bmatrix}
1&1& | &1/2&0 \\
3&1& | &0&1
\end{bmatrix}
\end{equation*}
$$
c. kali -2 dengan -1/2 agar menjadi 1
$$
\begin{equation*}
A=
\begin{bmatrix}
1&1& | &1/2&0 \\
0&1& | &3/4&-1/2
\end{bmatrix}
\end{equation*}
$$
d. kurangi 1 dengan 1 agar menjadi 0
$$
\begin{equation*}
A=
\begin{bmatrix}
1&0& | &-1/4&1/2\\
0&1& | &3/4&-1/2
\end{bmatrix}
\end{equation*}
$$

jadi invers dari matriks A adalah
$$
\begin{equation*}
A^{-1}=
\begin{bmatrix}
-1/4&1/2&\\
3/4&-1/2
\end{bmatrix}
\end{equation*}
$$

## Penyelesaian 4 persamaan dengan matriks invers  

$$
\\0x_1+0x_2+0x_3+x_4=-3\\
4x_1+2x_2+0x_3-4x_4=-2\\
-2x_1+0x_2+x_3+2x_4=-7\\
x_1+0x_2+0x_3+x_4=1\\
$$

$$
\begin{equation*}
A=
\begin{bmatrix}
0&0&0&1\\
4&2&0&-4\\
-2&0&1&2\\
1&0&0&1\\
\end{bmatrix}
\end{equation*}
$$




In [2]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [3]:
import numpy as np
A = np.array([[0,0,0,1,1,0,0,0], [4,2,0,-4,0,1,0,0], [-2,0,1,2,0,0,1,0], [1,0,0,1,0,0,0,1]])
print(A)

[[ 0  0  0  1  1  0  0  0]
 [ 4  2  0 -4  0  1  0  0]
 [-2  0  1  2  0  0  1  0]
 [ 1  0  0  1  0  0  0  1]]


In [4]:
# pindahkan baris 0 ke baris 3
B = RowSwap(A, 0, 3)
print(B)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 4.  2.  0. -4.  0.  1.  0.  0.]
 [-2.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [5]:
# tambahkan -4 kali baris 0 ke baris 1 
C = RowAdd(B, 0, 1, -4)
print(C)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  2.  0. -8.  0.  1.  0. -4.]
 [-2.  0.  1.  2.  0.  0.  1.  0.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [6]:
# tambahkan 2 kali baris 0 ke baris 2
D = RowAdd(C, 0, 2, 2)
print(D)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  2.  0. -8.  0.  1.  0. -4.]
 [ 0.  0.  1.  4.  0.  0.  1.  2.]
 [ 0.  0.  0.  1.  1.  0.  0.  0.]]


In [7]:
# kalikan baris 1 dengan 1/2
E = RowScale(D, 1, 1/2)
print(E)

[[ 1.   0.   0.   1.   0.   0.   0.   1. ]
 [ 0.   1.   0.  -4.   0.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [8]:
# tambahkan -1 kali baris 3 ke baris 0
F = RowAdd(E, 3, 0, -1)
print(F)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.  -4.   0.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [9]:
# Tambahkan 4 kali baris 3 ke baris 1
G = RowAdd(F, 3, 1, 4)
print(G)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.   0.   4.   0.5  0.  -2. ]
 [ 0.   0.   1.   4.   0.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [10]:
# tambahkan -4 kali baris 3 ke baris 2
H = RowAdd(G, 3, 2, -4)
print(H)

[[ 1.   0.   0.   0.  -1.   0.   0.   1. ]
 [ 0.   1.   0.   0.   4.   0.5  0.  -2. ]
 [ 0.   0.   1.   0.  -4.   0.   1.   2. ]
 [ 0.   0.   0.   1.   1.   0.   0.   0. ]]


In [11]:
# mencari x = A^-1 . b
H = np.array([[-1,0,0,1], [4,0.5,0,-2], [-4,0,1,2], [1,0,0,0]])
I = np.array([[-3], [-2], [-7], [1]])
print(H@I)

[[  4.]
 [-15.]
 [  7.]
 [ -3.]]


$$
\begin{equation*}
Matriks Inverse=
\begin{bmatrix}
-1&0&0&1\\
4&0.5&0&-2\\
-4&0&1&2\\
1&0&0&0\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
x=
\begin{bmatrix}
4\\
-15\\
7\\
-3\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
b=
\begin{bmatrix}
-3\\
-2\\
-7\\
1\\
\end{bmatrix}
\end{equation*}
$$

### UTS : Buat 4 persamaan Matriks dan cari Matriks Invers  

$$
\\4x_1+0x_2+0x_3+0x_4=8\\
0x_1+0x_2+2x_3+0x_4=2\\
0x_1+x_2+2x_3+0x_4=6\\
x_1+0x_2+0x_3+x_4=10\\
$$

$$
\begin{equation*}
A=
\begin{bmatrix}
4&0&0&0\\
0&0&2&0\\
0&1&2&0\\
1&0&0&1\\
\end{bmatrix}
\end{equation*}
$$


In [1]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [2]:
import numpy as np
A = np.array([[4,0,0,0,1,0,0,0], [0,0,2,0,0,1,0,0], [0,1,2,0,0,0,1,0], [1,0,0,1,0,0,0,1]])
print(A)

[[4 0 0 0 1 0 0 0]
 [0 0 2 0 0 1 0 0]
 [0 1 2 0 0 0 1 0]
 [1 0 0 1 0 0 0 1]]


In [3]:
B = RowSwap(A, 0, 3)
print(B)

[[1. 0. 0. 1. 0. 0. 0. 1.]
 [0. 0. 2. 0. 0. 1. 0. 0.]
 [0. 1. 2. 0. 0. 0. 1. 0.]
 [4. 0. 0. 0. 1. 0. 0. 0.]]


In [4]:
C = RowAdd(B, 0, 3, -4)
print(C)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  0.  2.  0.  0.  1.  0.  0.]
 [ 0.  1.  2.  0.  0.  0.  1.  0.]
 [ 0.  0.  0. -4.  1.  0.  0. -4.]]


In [5]:
D = RowSwap(C, 1, 2)
print(D)

[[ 1.  0.  0.  1.  0.  0.  0.  1.]
 [ 0.  1.  2.  0.  0.  0.  1.  0.]
 [ 0.  0.  2.  0.  0.  1.  0.  0.]
 [ 0.  0.  0. -4.  1.  0.  0. -4.]]


In [6]:
E = RowAdd(D, 2, 2, -1/2)
print(E)

[[ 1.   0.   0.   1.   0.   0.   0.   1. ]
 [ 0.   1.   2.   0.   0.   0.   1.   0. ]
 [ 0.   0.   1.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.  -4.   1.   0.   0.  -4. ]]


In [7]:
F = RowAdd(E, 2, 1, -2)
print(F)

[[ 1.   0.   0.   1.   0.   0.   0.   1. ]
 [ 0.   1.   0.   0.   0.  -1.   1.   0. ]
 [ 0.   0.   1.   0.   0.   0.5  0.   0. ]
 [ 0.   0.   0.  -4.   1.   0.   0.  -4. ]]


In [8]:
G = RowAdd(F, 3, 3, -5/4)
print(G)

[[ 1.    0.    0.    1.    0.    0.    0.    1.  ]
 [ 0.    1.    0.    0.    0.   -1.    1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.5   0.    0.  ]
 [ 0.    0.    0.    1.   -0.25  0.    0.    1.  ]]


In [9]:
H = RowAdd(G, 3, 0, -1/1)
print(H)

[[ 1.    0.    0.    0.    0.25  0.    0.    0.  ]
 [ 0.    1.    0.    0.    0.   -1.    1.    0.  ]
 [ 0.    0.    1.    0.    0.    0.5   0.    0.  ]
 [ 0.    0.    0.    1.   -0.25  0.    0.    1.  ]]


In [10]:
# A^-1.|A| = I
# jika Invers Matriks A dikali dengan Matriks A maka akan menghasilkan matriks identitas.
I = np.array([[0.25,0,0,0], [0,-1,1,0], [0,0.5,0,0], [-0.25,0,0,1]])
J = np.array([[4,0,0,0], [0,0,2,0], [0,1,2,0], [1,0,0,1]])
print(I@J)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# x = A^-1.b
# untuk mencari x kalikan matriks invers dengan b (konstanta)
K = np.array([[0.25,0,0,0], [0,-1,1,0], [0,0.5,0,0], [-0.25,0,0,1]])
L = np.array([[8], [2], [6], [10]])
print(K@L)

[[2.]
 [4.]
 [1.]
 [8.]]


$$
\begin{equation*}
Matriks Inverse=
\begin{bmatrix}
0.25&0&0&0\\
0&-1&1&0\\
0&0.5&0&0\\
-0.25&0&0&1\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
x=
\begin{bmatrix}
2\\
4\\
1\\
8\\
\end{bmatrix}
\end{equation*}
$$

$$
\begin{equation*}
b=
\begin{bmatrix}
8\\
2\\
6\\
10\\
\end{bmatrix}
\end{equation*}
$$