# Determinan  
Determinan adalah ukuran skalar dari suatu matriks atau suatu nilai yang dihitung dari elemen-elemen matriks. Matriks tersebut harus persegi/bujur sangkar dengan jumlah baris dan kolom harus sama. misalnya terdapat suatu matriks 2x2 (memiliki jumlah baris dan kolom yang sama) maka dapat dihitung determinanya.  

## Sifat-Sifat Determinan :  
1. Determinan dari suatu matriks identitas adalah 1 .

In [3]:
import numpy as np
C = np.array([[1,0], [0,1]])
D = np.array([[1,0,0], [0,1,0], [0,0,1]])
print("Matriks C : \n", C)
print("Matriks D : \n", D)

Matriks C : 
 [[1 0]
 [0 1]]
Matriks D : 
 [[1 0 0]
 [0 1 0]
 [0 0 1]]


In [4]:
E = np.linalg.det(C)
print(E)

1.0


- Penjelasan:
Dapat dilihat diatas bahwa determinan dari matriks identitas C 2x2 adalah 1 

2. Jika terdapat determinan C = determinan(A.B)  
                              = determinan(A).determinan(B)  
                              = A.A^1

In [14]:
A = np.array([[2,1], [3,2]])
B = np.linalg.inv(A)
A1 = np.linalg.det(A)
B1 = np.linalg.det(B)

print("determinan A : ", round(A1))
print("determinan B : ",round(B1))
C = A1*B1
print("det.A x det.B :",round(C))
print(A@B)

determinan A :  1
determinan B :  1
det.A x det.B : 1
[[1. 0.]
 [0. 1.]]


- Penjelasan : pada code diatas dapat dilihat bahwa jika determinan A x determinann B = 1 , sama dengan determinan A.A^1 yaitu 1 (pada variabel E).

3. Jika menukar baris pada suatu matriks, maka akan mengubah tanda determinanya juga. misalnya pada matriks D sebagai acuan determinan sebelum ada perubahan baris.

In [16]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("determinan matriks D : ",F)

determinan matriks F :  5


In [18]:
D1 = np.array([[1,1,1], [1,4,2],[3,2,1]])
D2 = np.linalg.det(D1)
print("determinan matriks D :", round(D2))

determinan matriks D : -5


- Penjelasan : dapat dilihat bahwa terdapat perubahan tanda determinan setelah ada perubahan baris 0 matriks ke baris 1 matriks. yaitu sebelum diubah determinan = 5, setelah diubah determinan= -5.

4. Jika menukar kolom pada suatu matriks, maka akan mengubah tanda dari determinan. 

In [6]:
import numpy as np
D = np.array([[1,4,2], [1,1,1],[3,2,1]])
E = np.linalg.det(D)
F = round(E)
print("matriks D :\n", D)
print("determinan D :", F)
D1 = np.array([[4,1,2], [1,1,1],[2,3,1]])
E1 = np.linalg.det(D1)
F1 = round(E1)
print("matriks D1 :\n", D1)
print("determinan D1:", F1)


matriks D :
 [[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan D : 5
matriks D1 :
 [[4 1 2]
 [1 1 1]
 [2 3 1]]
determinan D1: -5


- Penjelasan : terdapat perubahan tanda determinan pada matriks D setelah kolom 0 di pindah pada kolom 1, yang awal determinanya 5 menjadi -5 

5. Jika baris dari suatu matriks merupakan kelipatan dari baris lain maka determinanya 0. kelipatan bisa 2 kali, 3 kali, dst.

In [7]:
import numpy as np
P = np.array([[1,4,2], [2,8,4], [3,2,1]])
print(np.linalg.det(P))

0.0


- Penjelasan : pada matriks P baris ke 1 merupakan kelipatan2 kali dari baris ke 0, jadi determinanya yait 0

6. Jika kolom dari suatu matriks merupakan kelipatan dari kolom lain, maka determinan = 0.

In [8]:
import numpy as np
Q = np.array([[1,4,2], [2,8,3], [1,4,1]])
print(np.linalg.det(Q))

0.0


- Penjelasan : Pada matriks Q kolom 1 merupakan 4 kali dari kolom 0, sehingga ada kelipatan antar kolom maka determinanya adalah 0

7. Determinan A = determinan A transpose, jumlah determinan suatu matriks A sama dengan determinan A transpose.

In [11]:
# det A = det A transpose
import numpy as np
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
A_T = np.transpose(A)
B = np.linalg.det(A)
C = np.linalg.det(A_T)
print("determinan A : \n", round(B))
print("determinan A transpose :\n", round(C))

determinan A : 
 5
determinan A transpose :
 5


8. Matriks segitiga atas : jika dibawah diagonal utama [1,1,1] adalah 0, meskipun diatas diagonal utama tidak nol. Sedangkan Matriks segitiga bawah : jika diatas diagonal utama [1,1,1] adalah 0, meskipun dibawah diagonal utama tidak nol. jika melakukan operasi baris elementer tidak akan merubah determinan matriks tersebut.

In [13]:
def RowSwap(A,k,l):
# =============================================================================
#     A is a NumPy array.  RowSwap will return duplicate array with rows
#     k and l swapped.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        temp = B[k][j]
        B[k][j] = B[l][j]
        B[l][j] = temp

    return B

def RowScale(A,k,scale):
# =============================================================================
#     A is a NumPy array.  RowScale will return duplicate array with the
#     entries of row k multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[k][j] *= scale

    return B

def RowAdd(A,k,l,scale):
# =============================================================================
#     A is a numpy array.  RowAdd will return duplicate array with row
#     l modifed.  The new values will be the old values of row l added to
#     the values of row k, multiplied by scale.
# =============================================================================
    m = A.shape[0]  # m is number of rows in A
    n = A.shape[1]  # n is number of columns in A

    B = np.copy(A).astype('float64')

    for j in range(n):
        B[l][j] += B[k][j]*scale

    return B

In [45]:
import numpy as np 
A = np.array([[1,4,2], [1,1,1],[3,2,1]])
print(A)
A1 = np.linalg.det(A)
print("determinan : ", round(A1))

[[1 4 2]
 [1 1 1]
 [3 2 1]]
determinan A :  5


In [46]:
B = RowAdd(A, 0, 1, -1)
print(B)
B1 = np.linalg.det(B)
print("deteminan setelah ada OBE : ", round(B1))

[[ 1.  4.  2.]
 [ 0. -3. -1.]
 [ 3.  2.  1.]]
deteminan setelah ada OBE :  5


- Penjelasan : meskipun telah ada operasi baris elementer, tanda determinan tetap. 

### Cofactor Expansion  

Cofactor expansion digunakan untuk mencari determinan dari suatu matriks dengan memanfaatkan kofaktor. Kofaktor merupakan  suatu elemen dalam suatu matriks ditentukan oleh minor elemen tersebut yang diperoleh dengan menghilangkan baris dan kolom yang memuat elemen tersebut.  

Rumus cofactor:
$C_ij = (−1)^{(𝑖+𝑗)}. 𝑑𝑒𝑡(M_𝑖𝑗)$  

Misalnya mencari determinan matriks 4x4 dengan cofactor expansion. 
$$
\begin{equation*}
A=
\begin{bmatrix}
2&4&1&2 \\
1&3&1&1 \\
2&3&2&4 \\
2&2&1&4 \\
\end{bmatrix}
\end{equation*}
$$  

- Menggunakan baris 1 = $a_{11} c_{11} + a_{12} c_{12} + a_{13} c_{13} + a_{14} c_{14}$  
- Kemudian cari kofaktor matriks A dengan :
$$
c_{11}=(-1)^{1+1}.det(M_{11})\\
c_{12}=(-1)^{1+2}.det(M_{12})\\
c_{13}=(-1)^{1+3}.det(M_{13})\\
c_{14}=(-1)^{1+4}.det(M_{14})\\
$$  

- Kemudian cari determinan matriks minor dari matriks A :  

**1. Detrminan M11**  

$
\begin{matrix} \\
     M_{11} \space = \begin{bmatrix} 
    3&1&1 \\
    3&2&4 \\
    2&1&4 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  
$
Menggunakan \space baris \space 1 = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} \\
$  

$
c_{11} = (-1)^{1+1}. det(M_{11}) = (-1)^{1+1}det(
\begin{matrix}
  \begin{bmatrix}
    2&4 \\
    1&4
  \end{bmatrix}) 
\end{matrix} = 1.4
$

$
c_{12} = (-1)^{1+2}det(M_{12}) = (-1)^{1+2}det
\begin{matrix}(
\begin{bmatrix}
    3&4 \\
    2&4
\end{bmatrix}) 
\end{matrix} = -1.4
$

$
c_{13} = (-1)^{1+3}det(M_{13}) = (-1)^{1+3}det
\begin{matrix}(
\begin{bmatrix}
    3&2 \\
    2&1
\end{bmatrix})
\end{matrix} = 1.-1
$  

$
a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} = 3.1.4 + 1.-1.4 + 1.1.-1 \\ 
$  

$
det(M_{11}) \space = 12+ -4 + -1 =  7
$  
Determinan $M_{11}$ adalah **7** 


 






**2. Determinan M12**  
Mencari determinan dari $M_{12}$ 
$
\begin{matrix} \\
 M_{12} \space  = \begin{bmatrix} 
    1&1&1 \\
    2&2&4 \\
    2&1&4 \\
  \end{bmatrix} \\ \\
\end{matrix} \\
$  


$
Menggunakan \space Baris \space 1 = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} 
$

$
c_{11} = (-1)^{1+1}det(M_{11}) = (-1)^{1+1} det
\begin{matrix}(
  \begin{bmatrix}
   2&4 \\
   1&4 
  \end{bmatrix})
\end{matrix} = 1.4
$  

$
c_{12} = (-1)^{1+2}det(M_{12}) = (-1)^{1+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&4 \\
   2&4
  \end{bmatrix})
\end{matrix} = -1.0
$  

$
c_{13} = (-1)^{1+3}det(M_{13}) = (-1)^{1+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&2 \\
    2&1
  \end{bmatrix})
\end{matrix}   = 1.-2
$  

$
a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} = 1.1.4 + 1.-1.0 + 1.1.-2 
$  

$
det(M_{22}) \space= 4 + 0 + (-2) =  2
$  

Determinan dari $M_{12}$ adalah **2** 

**3. Determinan M13**  
Mencari determinan dari $M_{13}$
$
\begin{matrix} 
 M_{13} \space = \begin{bmatrix} 
    1&3&1 \\
    2&3&4 \\
    2&2&4 \\
  \end{bmatrix} 
\end{matrix} 
$  

$
Menggunakan \space Baris \space 1 = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} \\
$  

$
c_{11} = (-1)^{1+1}det(M_{11}) = (-1)^{1+1} det
\begin{matrix}(
  \begin{bmatrix}
   3&4 \\
   2&4 
  \end{bmatrix})
\end{matrix}   = 1.4
$  

$
c_{12} = (-1)^{1+2}det(M_{12}) = (-1)^{1+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&4 \\
   2&4
  \end{bmatrix})
\end{matrix}  = -1.0
$  

$
c_{13} = (-1)^{1+3}det(M_{13}) = (-1)^{1+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&3 \\
    2&2
  \end{bmatrix})
\end{matrix}  = 1.-2
$  

$
a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} = 1.1.4 + 3.-1.0 + 1.1.-2 \\ 
$  

$
det(M_{13}) \space = 4 + 0 + -2 = 2
$  
Determinan dari $M_{13}$ adalah **2**  

**4. Determinan M14**  
Mencari determinan dari $M_{14}$
$
\begin{matrix} 
 M_{14} \space = \begin{bmatrix} 
    1&3&1 \\
    2&3&2 \\
    2&2&1 \\
  \end{bmatrix} 
\end{matrix} 
$  

$
Menggunakan \space Baris \space 1 = a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} \\
$  

$
c_{11} = (-1)^{1+1}det(M_{11}) = (-1)^{1+1} det
\begin{matrix}(
  \begin{bmatrix}
   3&2 \\
   2&1 
  \end{bmatrix})
\end{matrix}   = 1.-1
$  

$
c_{12} = (-1)^{1+2}det(M_{12}) = (-1)^{1+2} det 
\begin{matrix}(
  \begin{bmatrix}
   2&2 \\
   2&1
  \end{bmatrix})
\end{matrix}  = -1.-2
$  

$
c_{13} = (-1)^{1+3}det(M_{13}) = (-1)^{1+3} det
\begin{matrix}(
  \begin{bmatrix}
    2&3 \\
    2&2
  \end{bmatrix})
\end{matrix}  = 1.-2
$  

$
a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} = 1.1.-1 + 3.-1.-2 + 1.1.-2 \\ 
$  

$
det(M_{14}) \space = -1 + 6 + -2 = 3
$  
Determinan dari $M_{14}$ adalah **3**  

**Diketahui bahwa :**
$
det(M_{11}) = 7  
$

$
det(M_{12}) = 2 
$

$ 
det(M_{13}) = 2  
$

$
det(M_{14}) = 3  
$  

Masukkan nilai nilai determinan yang telah diketahui dari Matriks-matriks minor: 

$
c_{11} = (-1)^{1+1}det(M_{11}) = 1.7  
$

$
c_{12} = (-1)^{1+2}det(M_{12}) = -1.2
$  

$
c_{13} = (-1)^{1+3}det(M_{13}) = 1.2
$  

$
c_{14} = (-1)^{1+4}det(M_{14}) = -1.3 \\ 
$  

$
a_{11}c_{11} + a_{12}c_{12} + a_{13}c_{13} + a_{14}c_{14} = 2.1.7 + 4.-1.2 + 1.1.2 + 2.-1.3 \\
$  

$
det(A) = 14 + (-8) + 2 + (-6) = 2
$    
  
**Jadi Determinan dari Matriks A = 2**

In [12]:
import numpy as np
A = np.array([[2,4,1,2], [1,3,1,1], [2,3,2,4], [2,2,1,4]])
B = np.linalg.det(A)
print("Matriks A: \n", A)
print()
print("Determinan A : ", round(B))

Matriks A: 
 [[2 4 1 2]
 [1 3 1 1]
 [2 3 2 4]
 [2 2 1 4]]

Determinan A :  2


Dapat dilihat bahawa hasil perhitungan manual mencari determinan dengan kofaktor sama dengan perhitungan menggunakan python yaitu 2.