# Aljabar Matriks

Matriks merupakan susunan bilangan real yang dapat diidentifikasi baris dan kolom nya yang ditempatkan didalam kurung siku. Matriks dapat dinotasikan dengan huruf kapital seperti A,B, dan seterusnya. Didalam matriks terdapat elemen-elemen matriks yang dinotasikan dengan huruf kecil yang setiap elemen memiliki baris dan kolom yang berbeda, seperti $a_{ij}=$ a elemen, i baris, j kolom. contoh: $a_{12}$ artinya elemen a terletak dibaris 1 dan kolom ke 2.  

* Ukuran matriks ditentukan oleh jumlah baris dan kolom.  
contoh : Matriks A berukuran 3x3 (3 baris 3 kolom)
$
A=
\begin{bmatrix}
2 & 4 & 5\\
4 & 6 & 9
\end{bmatrix}
$


## Jenis-jenis matriks:
1. Matriks nol, matriks yang semua elemen
penyusunnnya nol.
2. Matriks baris, matriks yang elemennya hanya satu baris.
3. Matriks kolom, matriks yang elemennya hanya satu kolom.
4. Matriks persegi adalah matriks yang mempunyai jumlah baris dan kolom yang sama.
5. Matriks diagonal,matriks persegi yang semua elemen di luar diagonal utamanya bernilai nol.
6. Matriks skalar, matriks yang elemen pada diagonal utamanya sama dan elemen diluar diagonal bernilai nol.
7. Matriks identitas, matriks skalar yang elemen pada diagonal utamanya sama dengan satu.
8. Matriks simetri, matriks persegi yang sama dengan transpose matriks itu sendiri.
9. Matriks simetri miring, matriks persegi yang sama dengan negatif matriks transposnya
10. Matriks segitiga atas, matriks persegi yang elemen-elemen di bawah diagonal utamanya adalah nol.
11. Matriks segitiga bawah, matriks persegi yang elem-elemen di atas diagonal utamanya adalah nol.
12. Matriks tranpose, matriks yang mengubah elemen dari baris menjadi kolom. 

## Implementasi Matriks dengan Numpy  

In [1]:
import numpy as np
A = np.array([[1,3,6],[2,1,5],[4,2,1]])
B = np.array([[3,1,6],[5,5,3],[5,8,9]])
C = np.array([[4,5],[5,0],[7,8]])
D = np.array([[3,3,6],[5,7,3],[5,8,8]])

print("A=\n",A)
print("B=\n",B)
print("C=\n",C)
print("D=\n",D)
print("\n")
print("Ukuran matriks :",A.shape) #ukuran matriks
print("Jumlah baris :", A.shape[0])# jumlah baris
print("Jumlah kolom :", A.shape[1])# jumlah kolom

A=
 [[1 3 6]
 [2 1 5]
 [4 2 1]]
B=
 [[3 1 6]
 [5 5 3]
 [5 8 9]]
C=
 [[4 5]
 [5 0]
 [7 8]]
D=
 [[3 3 6]
 [5 7 3]
 [5 8 8]]


Ukuran matriks : (3, 3)
Jumlah baris : 3
Jumlah kolom : 3


Dengan metode *Shape* kita dapat mengakses ukuran matriks, berdasarkan jumlah baris dan kolom dalam array. Contoh: Matriks A memilki ukuran 3x3 dengan rincian 3 baris dan 3 kolom.

In [2]:
y = np.random.randint(5,size=(3,3)) # menampilkan angka random dengan rentang 0-5 dengan ukuran matriks 3x3
print(y)

[[2 2 4]
 [4 0 1]
 [2 3 4]]


## Operasi-operasi Matriks  

1. ***Penjumlahan Matriks***  
matriks dapat dijumlahkan apabila ukuran matriks sama, berdasarkan jumlah baris dan kolom yang sama.  

* Sifat-sifat Penjumlahan matriks :

Contoh Penjumlahan Matriks  

$$
A = 
\begin{bmatrix}
1&3&6\\
2&1&5\\
4&2&1
\end{bmatrix}

B =
\begin{bmatrix}
3&1&6\\
5&5&3\\
5&8&9
\end{bmatrix}\\
$$

$$
A + B =
\begin{bmatrix}
1+3&3+1&6+6\\
2+5&1+5&5+3\\
4+5&2+8&1+9
\end{bmatrix}
$$

$$
=
\begin{bmatrix}
4&4&12\\
7&6&8\\
9&10&10
\end{bmatrix}
$$

In [3]:
# Penjumlahan Matriks
import numpy as np
A = np.array([[1,3,6],[2,1,5],[4,2,1]])
B = np.array([[3,1,6],[5,5,3],[5,8,9]])
C = np.array([[4,5],[5,0],[7,8]])
D = np.array([[3,3,6],[5,7,3],[5,8,8]])
print("A+B =\n", A+B)

A+B =
 [[ 4  4 12]
 [ 7  6  8]
 [ 9 10 10]]


Penjelasan :  
a. Matriks $A$ dan $B$ berhasil dijumlahkan karena memiliki ukuran matriks yang sama yaitu $3x3$.  
b. Sedangkan matriks $A$ dan $C$ tidak bisa dijumlahkan karena berbeda ukuran matriksnya yaitu $A (3x3), C (3x2)$

2. ***Pengurangan matriks***  
matriks dapat dikurangi apabila ukuran matriks sama, berdasarkan jumlah baris dan kolom yang sama.  

contoh pengurangan matriks :

B =
\begin{bmatrix}
    3&1&6\\
    5&5&3\\
    5&8&9
\end{bmatrix}
D =
\begin{bmatrix}
    3&3&6\\
    5&7&3\\
    5&8&8
\end{bmatrix}
B-D =
\begin{bmatrix}
    3-3&1-3&6-6\\
    5-5&5-7&3-3\\
    5-5&8-8&9-8
\end{bmatrix}
hasil =
\begin{bmatrix}
    0&-2&0\\
    0&-2&0\\
    0&0&1
\end{bmatrix}

In [4]:
# Pengurangan Matriks
import numpy as np
A = np.array([[1,3,6],[2,1,5],[4,2,1]])
B = np.array([[3,1,6],[5,5,3],[5,8,9]])
C = np.array([[4,5],[5,0],[7,8]])
D = np.array([[3,3,6],[5,7,3],[5,8,8]])
print("B-D=\n", B-D)

B-D=
 [[ 0 -2  0]
 [ 0 -2  0]
 [ 0  0  1]]


Penjelasan :

1. Matriks $B$ dan $D$ dapat dikurangi karena memiliki ukuran matriks yang sama yaitu $3x3$.
2. Sedangkan matriks $D$ dan $C$ tidak dapat dikurangi karena berbeda ukuran matriksnya yaitu $D(3x3), C(3x2)$

5. ***Perkalian Matriks***  
* Suatu matriks dapat dikalikan, jika jumlah kolom dari matrik pertama sama dengan jumlah baris matrik kedua. untuk mencari Ordo matriks hasil perkalian adalah dengan mengali jumlah baris matriks pertama dengan jumlah kolom matriks kedua. perkalian matrik dilakukan dengan mengalikan baris dan kolom.

Misalnya : matriks A = 2x2 dikalikan dengan matriks B = 2x2. 

$$
A=
\begin{bmatrix}
1&3\\
2&1\\
\end{bmatrix}
B=
\begin{bmatrix}
3&1\\
5&5\\
\end{bmatrix}\\
$$
$$
A*B =
\begin{bmatrix}
1x3+3x5&1x1+3x5\\
2x3+1x5&2x1+1x5\\
\end{bmatrix}
=
\begin{bmatrix}
18&16\\
11&7\\
\end{bmatrix}
$$

* Penjelasan :  
1. Matriks A memiliki jumlah kolom : 2 , Matriks B memiliki jumlah baris : 2 (jumlah sama)  
2. Ordo : baris A x kolom B = 2 X 2
              

In [5]:
# Perkalian matriks, c sebagai skalar
import numpy as np
A = np.array([[1,3,6],[2,1,5],[4,2,1]])
B = np.array([[3,1,6],[5,5,3],[5,8,9]])
c = 3
print('c(AB)\n',c*(A@B))
print('(cA)B\n',(c*A)@B)
print('A(cB)\n',A@(c*B))

c(AB)
 [[144 192 207]
 [108 141 180]
 [ 81  66 117]]
(cA)B
 [[144 192 207]
 [108 141 180]
 [ 81  66 117]]
A(cB)
 [[144 192 207]
 [108 141 180]
 [ 81  66 117]]


4. ***Matriks Transpose***  
matriks baru yang diperoleh dengan menukar baris menjadi kolom dari matriks aslinya. Jadi, elemen-elemen pada baris akan ditukar menjadi elemen-elemen pada kolom, ataupun sebaliknya. Matriks A transpose dinotasikan dengan $A^T$  

* sifat-sifat matriks transpose:  

a. $(A^T)^T = A$  
b. $(A+B)^T = A^T+B^T$  
c. $(cA)^T = cA^T$  
d. $(AB)^T = B^TA^T$

contoh matriks transpose :  

$$
A =
\begin{bmatrix}
2&4&6\\
8&1&7
\end{bmatrix}

A^T = 
\begin{bmatrix}
2&8\\
4&1\\
6&7
\end{bmatrix}
$$


In [1]:
import numpy as np
C = np.array([[4,5],[5,0],[7,8]])
C_T = C.transpose()
print('matrik C sebelum di transpose=\n', C)
print('matrik C setelah di transpose=\n',C_T)
print('ukuran C_transpose adalah',C_T.shape)

matrik C sebelum di transpose=
 [[4 5]
 [5 0]
 [7 8]]
matrik C setelah di transpose=
 [[4 5 7]
 [5 0 8]]
ukuran C_transpose adalah (2, 3)


## Program untuk mengalikan matriks 2x2 dengan for 

In [2]:
def matrix_multiplication(matrix_a, matrix_b):
    """
    Fungsi untuk perkalian matriks

    catatan:
        matrix_a : Matriks pertama
        matrix_b : Matriks kedua

    Returns:
        Matriks yang dihasilkan setelah perkalian
    """

    # Jumlah Kolom pada Matriks Pertama (a) Harus Sama dengan Jumlah Baris pada Matriks Kedua (b):
    if len(matrix_b[0]) != len(matrix_a):
        raise ValueError("tidak sesuai")

    resultant_matrix = [[0 for _ in range(len(matrix_b[0]))] for _ in range(len(matrix_a))]

    # perkalian matriks dengan nested for
    for baris_a in range(len(matrix_a)):
      for kolom_b in range(len(matrix_b[0])):
        result = 0
        for elemen in range(len(matrix_a[0])):
          result += matrix_a[baris_a][elemen] * matrix_b[elemen][kolom_b]
        resultant_matrix[baris_a][kolom_b] = result
    return resultant_matrix

# contoh matriks
matrix_a = [[1,3], [2,1]]
matrix_b = [[3,1], [5,5]]

resultant_matrix = matrix_multiplication(matrix_a, matrix_b)
print("Hasil perkalian matriks :")
for row in resultant_matrix:
    print(row)


Hasil perkalian matriks :
[18, 16]
[11, 7]
